### ISSUE TITLE
Test to ensure that compartment sizes are always positive

### ISSUE THREAD

**Issue by kokbent** [CDCgov/DynODE#85]
Currently dealing with negative compartment sizes 😵‍💫 and Tom says this needs to be a test lol

**Comment by arik-shurygin** [comment]
Closing this. In short this issue has stayed open because it was vague. We have a test already implemented to check for negative compartment sizes within #87. What this issue was likely asking for was a flag to set to raise warnings when negative compartment sizes are detected mid-run. Due to the nature of Jax running just-in-time compilation this has a pretty big hit on computational ability but is possible through `jnp.where()` and `jax.lax.cond`
